opt_in_rules:
- empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- colon
- comma
- control_statement

line_length: 200
function_body_length : 50
# they can set both implicitly with an array
type_body_length:
  - 100 # warning
  - 150 # error
# or they can set both explicitly
file_length:
  warning: 150
  error: 250
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 100
